DROP TABLE IF EXISTS daily_db_users;
CREATE TABLE IF NOT EXISTS daily_db_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    pwd VARCHAR(255) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    insert_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO daily_db_users (uid, pwd) VALUES ('test', '$2b$12$DTeqZwmAZT4fK/wt3jRFC.QSMtF8BPCQFIyQfsKxyzkhuB0.hNCRS') ON DUPLICATE KEY UPDATE update_date = CURRENT_TIMESTAMP;
INSERT INTO daily_db_users (uid, pwd) VALUES ('test2', 'test') ON DUPLICATE KEY UPDATE update_date = CURRENT_TIMESTAMP;
