DROP TABLE IF EXISTS daily_db_users;
CREATE TABLE IF NOT EXISTS daily_db_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    pwd VARCHAR(255) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    insert_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO daily_db_users (uid, pwd) VALUES ('test', '$2b$12$zujjjJ3C36ZrWtVu/lpibueErLgjAAvwIkH70819YoAnItG3gaRY6') ON DUPLICATE KEY UPDATE update_date = CURRENT_TIMESTAMP;
INSERT INTO daily_db_users (uid, pwd) VALUES ('test2', 'test') ON DUPLICATE KEY UPDATE update_date = CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS daily_db_projects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    user_id INT NOT NULL,
    root_dir VARCHAR(200) NOT NULL,
    if_script VARCHAR(10000) NOT NULL,
    state VARCHAR(20) DEFAULT 'new',
    insert_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES daily_db_users(id)
);
